### PR TITLE
Feat: Add fetch options which enables passing Authorization headers

### PR DESCRIPTION
**Pull request by madole**
Sometimes an Auth Token is needed to access data behind a proxy or some other private network. 

For fetching tiles this is fine as you can use the `transformRequest` callback in the Mapbox constructor, but for the `identify` and `getServiceDetails` calls, this goes directly from the package to your ESRI endpoint so adding optional fetch options allows us to pass those Authorization headers into the fetch calls

### CODE REVIEW

**Comment by rowanwins** [comment]
Hey @madole 

Thanks for a really thorough PR (explanation and code). I'll take a look over the next couple of days and hopefully get a release out incorporating this. I'll have a scrounge around and see if I can find some non-public services to test on.

Cheers
Rowan

**Comment by madole** [comment]
Much appreciated. Let me know if there's anything I can do to help out.

**Comment by rowanwins** [comment]
Thanks @madole for the contribution - now published as 0.0.4

**Comment by PedroVenancio** [comment]
Hi @rowanwins and @madole 

I'm trying to use fetch options to pass the token to a non-public service, but I can't see how it should be done. Here is what I'm trying:

```
var esri_test = new mapboxglEsriSources.DynamicMapService('test', map, {
                url: 'https://services.test.com/server/rest/services/TEST/TEST/MapServer',
                layers: [1],
                fetchOptions: {
                    token: tokenVariable,
                    },
            })
```
But the request does not include the token parameter:
`https://services.test.com/server/rest/services/TEST/TEST/MapServer/export?bbox=-1878516.4071364924,4383204.9499851465,-1565430.3392804079,4696291.017841227&bboxSR=3857&imageSR=3857&format=png24&layers=show:1&transparent=true&size=256,256&f=image`

So, how fetchOptions should be invoked? I didn't find any example of use in https://frontiersi.github.io/mapbox-gl-esri-sources/#/examples/dynamic-map-service-basic

Thank you very much!

**Comment by rowanwins** [comment]
@PedroVenancio currently the fetchOptions only works for the other requests like `identify()`, for the actual tiles then you can utilise the `transformRequest` option in the map constructor, see an example here
https://maplibre.org/maplibre-gl-js-docs/api/properties/#requestparameters

This probably isn't overly intuitive and we could extend what we've got to include adding the fetchOptions to the actual tile requests.

**Comment by PedroVenancio** [comment]
Hi @rowanwins 

The simplest way I've found was adding `token` as a new defaultEsriOptions in https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/src/DynamicMapService.js:


```
            this._defaultEsriOptions = {
                layers: false,
                token: false,
                layerDefs: false,
                format: 'png24',
                dpi: 96,
                transparent: true,
                getAttributionFromService: true
            };


        get _tokenStr () {
            let toks = this.options.token;
            if (!toks) return ''
            return `${toks}`
        }
        
        get _source () {
            const tileSize = this.rasterSrcOptions ? this.rasterSrcOptions.tileSize ? this.rasterSrcOptions.tileSize : 256 : 256;
            // These are the bare minimum parameters
            const params = new URLSearchParams({
                bboxSR: 3857,
                imageSR: 3857,
                format: this.options.format,
                layers: this._layersStr,
                token: this._tokenStr,
                transparent: this.options.transparent,
                size: [tileSize, tileSize],
                f: 'image'
            });
            
            
        identify (lnglat, returnGeometry) {
            const canvas = this._map.getCanvas();
            const bounds = this._map.getBounds().toArray();
            returnGeometry = returnGeometry ? returnGeometry : false;
            const params = new URLSearchParams({
                sr: 4326,
                geometryType: 'esriGeometryPoint',
                geometry: JSON.stringify({
                    x: lnglat.lng,
                    y: lnglat.lat,
                    spatialReference: {
                        wkid: 4326
                    }
                }),
                tolerance: 3,
                returnGeometry,
                imageDisplay: `${canvas.width},${canvas.height},96`,
                mapExtent: `${bounds[0][0]},${bounds[0][1]},${bounds[1][0]},${bounds[1][1]}`,
                layers: this._layersStrIdentify,
                token: this._tokenStr,
                layerDefs: this._layerDefs,
                time: this._time,
                f: 'json'
            });
```

It seems to work, but I don't know if this is the best way to do it.

**Comment by PedroVenancio** [comment]
Hi @rowanwins 

My proposal is not a good solution, because some public servers return
```
{
  "error": {
    "code": 498,
    "message": "Invalid Token",
    "details": []
  }
}
```
when using `&token=` parameter.

**Comment by PedroVenancio** [comment]
Ok, I changed it a bit and put token as an optional parameter:

```
            this._defaultEsriOptions = {
                layers: false,
                token: false,
                layerDefs: false,
                format: 'png24',
                dpi: 96,
                transparent: true,
                getAttributionFromService: true
            };


        get _tokenStr () {
            let toks = this.options.token;
            if (!toks) return false
            return `${toks}`
        }
        
        get _source () {
            const tileSize = this.rasterSrcOptions ? this.rasterSrcOptions.tileSize ? this.rasterSrcOptions.tileSize : 256 : 256;
            // These are the bare minimum parameters
            const params = new URLSearchParams({
                bboxSR: 3857,
                imageSR: 3857,
                format: this.options.format,
                layers: this._layersStr,
                transparent: this.options.transparent,
                size: [tileSize, tileSize],
                f: 'image'
            });
            // These are optional params
            if (this._tokenStr) params.append('token', this._tokenStr);
            
            
        identify (lnglat, returnGeometry) {
            const canvas = this._map.getCanvas();
            const bounds = this._map.getBounds().toArray();
            returnGeometry = returnGeometry ? returnGeometry : false;
            const params = new URLSearchParams({
                sr: 4326,
                geometryType: 'esriGeometryPoint',
                geometry: JSON.stringify({
                    x: lnglat.lng,
                    y: lnglat.lat,
                    spatialReference: {
                        wkid: 4326
                    }
                }),
                tolerance: 3,
                returnGeometry,
                imageDisplay: `${canvas.width},${canvas.height},96`,
                mapExtent: `${bounds[0][0]},${bounds[0][1]},${bounds[1][0]},${bounds[1][1]}`,
                layers: this._layersStrIdentify,
                layerDefs: this._layerDefs,
                time: this._time,
                f: 'json'
            });
            if (this._tokenStr) params.append('token', this._tokenStr);
```

**Pull request merged**
